### ISSUE TITLE
Replace jcenter hosting

### ISSUE THREAD

**Issue by hannomalie** [zopaUK/ktor-opentracing#26]
Hi there!

Thanks for your super nice project, we wan't to use it :)

I noticed that hosting is currently done on jcenter, which will be shut down soon (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/)

Can you please use a differnt hoster, ideally maven central?

Thx!
Hannes

**Comment by fstien** [comment]
Hi Hannes, thanks for your kind message. 
I am planning on moving this to maven central; I hope to do this very soon. I'll let you know when done. 
Best, Francois

**Comment by franck-agoradcm** [comment]
Hi @fstien,

As Bintray is [no longer available as of yesterday](https://status.bintray.com/incidents/5l4dhjq7g7mn), is the move to Maven Central likely to happen any time soon?

Thanks

**Comment by fstien** [comment]
Hey @hannomalie , @franck-agoradcm , sorry for the delay here. The latest version (`0.3.5`) is available from Maven Central; https://search.maven.org/artifact/com.zopa/ktor-opentracing/0.3.5/jar
Please note that the groupId has changed to `com.zopa` . Please let me know if you have any issues. 
Francois
