### ISSUE TITLE
Missing context request headers shouldn't create `info` level logs

### ISSUE THREAD

**Issue by tajobe** [zopaUK/ktor-opentracing#30]
At least in our use case, it's fairly common that the request will not contain the headers required for context propagation and this info log creates quite a bit of unnecessary spam in the log _for each request_: https://github.com/zopaUK/ktor-opentracing/blob/3cf825cdd1262c86642d624b9c2feb946d5029d8/src/main/kotlin/com/zopa/ktor/opentracing/OpenTracingServer.kt#L63

We can configure the log level for the `com.zopa.ktor.opentracing.Utils` logger as warn as a workaround, but it makes more sense to me for this to be a debug or even trace-level message

**Comment by fstien** [comment]
hey @tajobe , 
Thanks for pointing this out. I fixed this in the latest release; https://github.com/zopaUK/ktor-opentracing/releases/tag/0.3.3 .

**Comment by tajobe** [comment]
Thanks! I was able to confirm the new log level.
