### ISSUE TITLE
Advice on when/how to insert trace-id into logging context?

### ISSUE THREAD

**Issue by holyjak** [zopaUK/ktor-opentracing#7]
Hello! Thanks a lot for this library!

I would like to use [`MDC.put`](http://www.slf4j.org/api/org/slf4j/MDC.html#put(java.lang.String,java.lang.String)) to put the trace-id into the logging context so that it gets included in all logs. But when I should do that? I guess I would need to define my own phase and insert it between Features and OpenTracingStart. Or? Thank you!

**Comment by fstien** [comment]
Hi Jakub, Thanks for your message! 
As the `OpenTracingStart` phase is [inserted before the Features phase](https://github.com/zopaUK/ktor-opentracing/blob/7b0aae8bcb123fda430b1a0d9c8fa247eabb42c2/src/main/kotlin/com/zopa/ktor/opentracing/OpenTracingServer.kt#L44), I recommend that you intercept the Features phase.
You can add a code block to the phase in your module function as such:
```
intercept(ApplicationCallPipeline.Features) {
   MDC.put("traceId", GlobalTracer.get().activeSpan().context().toTraceId())
}
```
Please let me know if you have any questions! 
Francois

**Comment by holyjak** [comment]
Thanks a lot! I fixed that via 

```kotlin
    intercept(ApplicationCallPipeline.Features) {
        println("Intercept before: spanContext=" + current().spanContext)
        proceed()
        println("Intercept after: spanContext=" + current().spanContext)
    }
```

though I am not abandoning OpenTracing for OpenTelemetry. I will steal all the ideas from your code :-)

**Comment by fstien** [comment]
You're welcome! :)
